name: Build Dictionaries
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Build Dictionaries
        run: |
          mkdir dist
          pip3 install -r requirements.txt
          cd dist
          python3 ../krdict_conv.py -np -l all
          cd ..
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
